version: '3.7'
services: # the different images that will be running as containers

  vei_platform:
    build: . 
    image: dataintensive/vei_platform:${DJANGO_GIT_TAG}
    env_file:
      - .env

  vei_platform_test:
    build: . 
    image: dataintensive/vei_platform:${DJANGO_GIT_TAG}
    command: cd apps && python manage.py test
    env_file:
      - .env_test

  django_q:
    build: .
    image: dataintensive/vei_platform:${DJANGO_GIT_TAG}
    command: cd apps && python manage.py qcluster
    env_file:
      - .env
