services:

  vei_platform:
    build: .
    image: dataintensive/vei_platform:${DJANGO_GIT_TAG}
    env_file:
      - .env

  vei_platform_test:
    build: .
    image: dataintensive/vei_platform:${DJANGO_GIT_TAG}
    entrypoint: /entrypoint/entrypoint_tests.sh
    env_file:
      - .env_test

  django_q:
    build: .
    image: dataintensive/vei_platform:${DJANGO_GIT_TAG}
    entrypoint: /entrypoint/entrypoint_qcluster.sh
    env_file:
      - .env

  scripe_energy_prices:
    build: .
    image: dataintensive/vei_platform:${DJANGO_GIT_TAG}
    entrypoint: /entrypoint/entrypoint_energybot.sh
    env_file:
      - .env_energybot
