# Generated by Django 4.2.6 on 2023-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarestatelisting',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='solarestatelisting',
            name='commision',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='solarestatelisting',
            name='persent_from_profit',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
