# Generated by Django 4.2.6 on 2023-10-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0002_alter_solarestatelisting_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarestatelisting',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vei_platform.electricityfactory'),
        ),
    ]
