# Generated by Django 4.2.6 on 2023-10-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "vei_platform",
            "0006_remove_electricityfactory_fraction_on_platform_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="owner_name",
        ),
    ]
