# Generated by Django 4.2.6 on 2023-10-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0007_remove_bankaccount_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='legal_form',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.CreateModel(
            name='PlatformLegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vei_platform.legalentity')),
            ],
        ),
    ]
