# Generated by Django 4.2.6 on 2023-11-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0009_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_balance',
            field=models.BooleanField(default=True),
        ),
    ]
