# Generated by Django 4.2.6 on 2023-11-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0011_investementinlisting_delete_solarestateinvestor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SolarEstateListing",
            new_name="FactoryListing",
        ),
    ]
