# Generated by Django 4.2.6 on 2023-11-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0012_rename_solarestatelisting_factorylisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactoryListing',
            new_name='Campaign',
        ),
        migrations.RenameModel(
            old_name='InvestementInListing',
            new_name='InvestementInCampaign',
        ),
    ]
