# Generated by Django 4.2.6 on 2023-11-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0014_campaign_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investementincampaign",
            old_name="listing",
            new_name="campaign",
        ),
    ]
