# Generated by Django 4.2.6 on 2023-12-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0017_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vei_platform.userprofile'),
        ),
    ]
