# Generated by Django 4.2.6 on 2023-12-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0018_alter_teammember_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityFactoryComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('component_type', models.CharField(choices=[('PAN', 'Photovoltaic Panel'), ('INV', 'Invertor'), ('CON', 'Connector'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('power_in_kw', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=9, null=True)),
                ('count', models.IntegerField(default=1)),
                ('factory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vei_platform.electricityfactory')),
            ],
        ),
    ]
