# Generated by Django 4.2.6 on 2024-01-02 06:02

from django.db import migrations, models
import vei_platform.models.factory


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0019_electricityfactorycomponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityfactorycomponents',
            name='docfile',
            field=models.FileField(blank=True, default=None, null=True, upload_to=vei_platform.models.factory.user_file_upload_directory_path),
        ),
    ]
