# Generated by Django 4.2.6 on 2024-01-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0021_alter_electricityfactorycomponents_docfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricityfactorycomponents",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
