# Generated by Django 4.2.4 on 2024-05-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0028_alter_legalentitysources_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('UN', 'Under review'), ('Ac', 'Active'), ('CA', 'Canceled'), ('CO', 'Completed')], default='UN', max_length=2),
        ),
    ]
