# Generated by Django 4.2.4 on 2024-05-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0031_auto_20240508_0445"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electricityprice",
            name="month",
        ),
    ]
