# Generated by Django 4.2.4 on 2024-05-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0035_electricitypriceplan_billing_zone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricitypriceplan",
            name="slug",
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="electricitypriceplan",
            name="description",
            field=models.TextField(max_length=4096),
        ),
    ]
