# Generated by Django 4.2.4 on 2024-06-15 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vei_platform", "0040_alter_electricitypriceplan_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricitypriceplan",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
