# Generated by Django 4.2.4 on 2024-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vei_platform', '0042_electricityprice_check_start_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='electricityprice',
            name='check_start_date',
        ),
        migrations.AddConstraint(
            model_name='electricityprice',
            constraint=models.CheckConstraint(check=models.Q(('start_interval__lt', models.F('start_interval'))), name='check_start_date'),
        ),
    ]
