# Generated by Django 4.2.4 on 2024-06-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0043_remove_electricityprice_check_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="electricityprice",
            name="check_start_date",
        ),
    ]
