# Generated by Django 4.2.4 on 2024-06-23 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0045_alter_electricityprice_start_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricityprice",
            name="start_interval",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2024, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
