# Generated by Django 4.2.4 on 2024-08-05 04:19

from django.db import migrations
from djmoney.money import Currency


def reset_prices_currency(apps, schema_editor):
    ElectricityPricePlan = apps.get_model("vei_platform", "ElectricityPricePlan")
    ElectricityPrice = apps.get_model("vei_platform", "ElectricityPrice")
    for plan in ElectricityPricePlan.objects.all():
        currency = Currency(plan.currency)
        price_objs = ElectricityPrice.objects.filter(plan=plan)
        # Be aware that the update() method is converted directly to an SQL statement.
        # It is a bulk operation for direct updates.
        # It doesn’t run any save() methods on your models, or emit the
        # pre_save or post_save signals (which are a consequence of calling save()),
        # or honor the auto_now field option. If you want to save every item in a QuerySet and
        # make sure that the save() method is called on each instance, you don’t need any
        # special function to handle that. Loop over them and call save():
        price_objs.update(price_currency=currency)


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0048_userprofile_timezone"),
    ]

    operations = [
        migrations.RunPython(reset_prices_currency),
    ]
