# Generated by Django 4.2.4 on 2024-08-19 06:57

from django.db import migrations

def generate_electricity_factory_slugs(apps, schema_editor):
    ElectricityFactory = apps.get_model("vei_platform", "ElectricityFactory")
    for row in ElectricityFactory.objects.all():
        #row.slug = str(uuid.uuid4())
        row.save()



class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0051_remove_electricityfactoryproduction_month_and_more"),
    ]

    operations = [
        migrations.RunPython(
            generate_electricity_factory_slugs, reverse_code=migrations.RunPython.noop
        ),
    ]
