# Generated by Django 4.2.4 on 2024-08-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0052_factory_generate_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricityfactory",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="electricityfactory",
            name="factory_code",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="electricityfactory",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="electricityfactoryproduction",
            name="factory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vei_platform.electricityfactory",
            ),
        ),
    ]
