# Generated by Django 4.2.4 on 2024-09-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0053_electricityfactory_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investementincampaign",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="investementincampaign",
            name="investor_profile",
        ),
        migrations.DeleteModel(
            name="Campaign",
        ),
        migrations.DeleteModel(
            name="InvestementInCampaign",
        ),
    ]
