# Generated by Django 4.2.4 on 2024-09-03 05:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "vei_platform",
            "0055_electricityfactory_currency_electricityfactory_plan_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricityFactorySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BGN", "BGN лв"), ("EUR", "EUR €"), ("USD", "USD $")],
                        default="BGN",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "min_price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        default_currency="BGN",
                        max_digits=14,
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vei_platform.electricityfactory",
                    ),
                ),
            ],
        ),
    ]
