# Generated by Django 4.2.4 on 2024-11-04 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vei_platform.models.production
import vei_platform.models.restricted_file_field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vei_platform", "0057_remove_electricityfactoryschedule_min_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricityFactoryUploadedProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "docfile",
                    vei_platform.models.restricted_file_field.RestrictedFileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=vei_platform.models.production.user_document_upload_directory_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
