# Generated by Django 4.2.4 on 2024-11-05 14:12

from django.db import migrations, models
import django.db.models.deletion
import vei_platform.models.production
import vei_platform.models.restricted_file_field


class Migration(migrations.Migration):

    dependencies = [
        ("vei_platform", "0058_electricityfactoryuploadedproductionreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricityfactoryuploadedproductionreport",
            name="docfile",
            field=vei_platform.models.restricted_file_field.RestrictedFileField(
                default=None,
                upload_to=vei_platform.models.production.user_document_upload_directory_path,
            ),
        ),
        migrations.CreateModel(
            name="ElectricityFactoryProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        verbose_name="Month",
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vei_platform.electricityfactory",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vei_platform.electricityfactoryuploadedproductionreport",
                    ),
                ),
            ],
            options={
                "unique_together": {("factory", "year", "month")},
            },
        ),
    ]
