# Generated by Django 4.2.4 on 2024-12-04 14:00

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "vei_platform",
            "0059_alter_electricityfactoryuploadedproductionreport_docfile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="electricityfactoryproduction",
            name="reported_price_per_mwh",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=None,
                default_currency="BGN",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="electricityfactoryproduction",
            name="reported_price_per_mwh_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BGN", "BGN лв"), ("EUR", "EUR €"), ("USD", "USD $")],
                default="BGN",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
